controller_list:
  - name: arm_group_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - 1_Joint
      - 2_Joint
      - 3_Joint
      - 4_Joint
      - 5_Joint
      - 6_Joint